name: day_task
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/applogo.svg
    - assets/images/splash/splashimage.png
    - assets/images/auth/emailsuffixicon.svg
    - assets/images/auth/fullnamesuffixicon.svg
    - assets/images/auth/passwordsuffixicon.svg
    - assets/images/auth/agreebox1.svg
    - assets/images/auth/agreebox2.svg
    - assets/images/auth/googleicon.svg
    - assets/images/auth/showpassword1.svg
    - assets/images/auth/showpassword2.svg
    - assets/images/home/addicon.svg
    - assets/images/home/calendaricon.svg
    - assets/images/home/homeicon.svg
    - assets/images/home/messagesicon.svg
    - assets/images/home/notificationicon.svg
    - assets/images/home/searchicon.svg
    - assets/images/home/settingicon.svg
    - assets/images/tasks/arrowleft.svg
    - assets/images/tasks/calendaricon2.svg
    - assets/images/tasks/editicon.svg
    - assets/images/tasks/profileicon.svg
    - assets/images/tasks/tickicon.svg
    - assets/splash.png

  fonts:
    - family: Pilat Extended
      fonts:
        - asset: assets\fonts\pilat extended\PilatExtended-SemiBold.ttf
        - weight: 600
    - family: Inter
      fonts:
        - asset: assets\fonts\inter\Inter-Regular.ttf
        - weight: 400
        - asset: assets\fonts\inter\Inter-Medium.ttf
        - weight: 500
        - asset: assets\fonts\inter\Inter-SemiBold.ttf
        - weight: 600
